### ISSUE TITLE
[Solved] How to enable Error Handling function support?

### ISSUE THREAD

**Issue by coolaj86** [michal-choluj/express-async-await#2]
# Update

I've created a PR with the fix as https://github.com/michal-choluj/express-promisify-router/pull/3 and I've also published my own version with the fix, and updated docs:

- `npm install --save @root/async-router`
- [@root/async-router](https://github.com/therootcompany/async-router)

# Original

I've got a scenario where all four possible params can be passed in (which should only be called where there is an error) but instead it's only getting called every time, and with only 3 arguments `(req, res, next)`.

```js
var app = require('express-promisify-router').Router();
app.use('/', function (err, req, res, next) {
    // should only get called when there is an error
});
```

I'm trying to figure out what to change for this to work as expected.

So far I've been able to make it skip, but I don't think this actually works as expected.

```js
function wrapFunction(fn, that) {
        // ...
        if (4 == len && 4 !== args.length) {
                // the function is intended to handle errors,
                // but no error occurred in the previous iteration
                next();
                return;
        }
        // ...
}
```

**Comment by coolaj86** [comment]
My current workaround is to move the `errorhandler` middleware up to the top level as a true `express` app:

```js
var bigApp = express();
var app = Router();

bigApp.use('/', errorhandler());
bigApp.use('/', app)

app.use('/', ...)
```

**Comment by michal-choluj** [comment]
Thank you for your patience. I'm glad to inform you that I've finally resolved the issue and updated the library accordingly.
