### ISSUE TITLE
[Ann] New Active Maintainer

### ISSUE THREAD

**Issue by coolaj86** [michal-choluj/express-async-await#4]
Since I haven't heard back from the previous maintainer, I'm taking over maintenance at https://github.com/therootcompany/async-router

- [`@root/async-router`](https://www.npmjs.com/package/@root/async-router) on npm.

Now that the error handling bug has been fixed I believe that the fork is "complete", however, I'm actively using it in production projects and plan to continue to do so.

Please open any new issues over there.

Many thanks to @michal-choluj for bringing this about in such a simple and concise manner! 🙏

**Comment by michal-choluj** [comment]
I'm sorry for not being able to address this earlier. I've been quite busy lately, but I finally found a moment to update the code and implement the suggested fixes. Thank you for bringing it to my attention :)
